---
lang: ru
format:
    pdf:
        pdf-engine: xelatex
        include-in-header: ../files/exam_header.tex  # Custom LaTeX commands and preamble
---

# Определения и формулировки
<!-- Лекция 1: Линейная алгебра. Скорости сходимости -->
1. Положительно определённая матрица.
1. Евклидова норма вектора.
1. $p$-норма вектора.
1. Норма Фробениуса матрицы.
1. Спектральная норма матрицы.
1. Скалярное произведение двух векторов.
1. Скалярное произведение двух матриц, согласованное с нормой Фробениуса.
1. Собственные значения матрицы. Спектр матрицы.
1. Связь спектра матрицы и её определённости.
1. Спектральное разложение симметричной матрицы.
1. Сингулярное разложение матрицы.
1. Связь определителя и собственных чисел квадратной матрицы.
1. Связь следа и собственных чисел квадратной матрицы.
1. Линейная сходимость последовательности.
1. Сублинейная сходимость последовательности.
1. Сверхлинейная сходимость последовательности.
1. Квадратичная сходимость последовательности.
1. Тест корней для определения скорости сходимости последовательности.
1. Тест отношений для определения скорости сходимости последовательности.
<!-- Лекция 2: Дифференцирование. Линейный поиск -->
1. Градиент функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Гессиан функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Якобиан функции $f(x): \mathbb{R}^n \to \mathbb{R}^m$.
1. Аппроксимация Тейлора первого порядка $f^I_{x_0}(x)$ функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Аппроксимация Тейлора второго порядка $f^{II}_{x_0}(x)$ функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Связь дифференциала функции $df$ и градиента $\nabla f$ для функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Связь второго дифференциала функции $d^2f$ и гессиана $\nabla^2 f$ для функции $f(x): \mathbb{R}^n \to \mathbb{R}$.
1. Унимодальная функция.
1. Метод дихотомии.
1. Метод золотого сечения.
1. Условие достаточного убывания (Армихо) для неточного линейного поиска.
1. Условия Гольдштейна для неточного линейного поиска.
1. Условия Вульфа для неточного линейного поиска.
<!-- Лекция 3: Автоматическое дифференцирование -->
1. Forward chain rule: формула $\frac{\partial f}{\partial t}$ через $\frac{\partial x_i}{\partial t}$ для $f=f(x_1(t),\ldots,x_n(t))$.
1. Backward chain rule: формула $\frac{\partial L}{\partial v_k}$ через $\frac{\partial L}{\partial x_i}$ для скалярной $L$ и векторного узла $v_k$.
1. Идея gradient checkpointing для обратного режима AD.
<!-- Лекция 4: Выпуклость. PL. Сильная выпуклость -->
1. Аффинное множество. Аффинная комбинация. Аффинная оболочка.
1. Конус. Выпуклый конус. Коническая комбинация. Коническая оболочка.
1. Выпуклое множество. Выпуклая комбинация. Выпуклая оболочка.
1. Любые 2 операции с множествами, сохраняющие выпуклость.
1. Сумма Минковского.
1. Выпуклая функция.
1. Строго выпуклая функция.
1. Надграфик функции.
1. Множество подуровня (Лебега) функции.
1. Любые 2 операции с функциями, сохраняющие выпуклость.
1. Условие Поляка-Лоясиевича (градиентного доминирования).
1. Привести пример выпуклой, но не сильно выпуклой задачи линейных наименьших квадратов (возможно, с регуляризацией).
1. Привести пример сильно выпуклой задачи линейных наименьших квадратов (возможно, с регуляризацией).
<!-- Лекция 5: Критерии сильной выпуклости. Условия оптимальности -->
1. Дифференциальный критерий выпуклости первого порядка.
1. Дифференциальный критерий выпуклости второго порядка.
1. $\mu$-сильно выпуклая функция.
1. Дифференциальный критерий сильной выпуклости первого порядка.
1. Дифференциальный критерий сильной выпуклости второго порядка.
1. Необходимые условия безусловного локального экстремума.
1. Достаточные условия безусловного локального экстремума.
<!-- Лекция 6: Условная оптимизация. Лагранж, ККТ, двойственность -->
1. Общая задача математического программирования. Функция Лагранжа.
1. Теорема Каруша-Куна-Таккера: необходимые условия для задачи математического программирования.
1. Условие Слейтера.
1. Задача выпуклого программирования.
1. Лагранжева двойственная функция.
1. Двойственная задача.
1. Слабая двойственность. Зазор двойственности.
1. Сильная двойственность.
<!-- Лекция 7: Линейное программирование. Симплекс -->
1. Задача линейного программирования. Стандартная форма задачи ЛП.
1. Симплекс-метод (достаточно описать шаги алгоритма).
1. Двухфазный симплекс-метод.
1. Сходимость симплекс-метода.
1. Двойственная задача к задаче ЛП.
<!-- Лекция 8: Градиентный спуск. Сходимость -->
1. Направление антиградиента как направление наискорейшего локального убывания.
1. Дифференциальное уравнение градиентного потока.
1. Метод градиентного спуска.
1. Наискорейший спуск.
1. Как направлены градиенты на двух соседних итерациях метода наискорейшего спуска по отношению друг к другу?
1. Характер сходимости градиентного спуска для гладких невыпуклых функций в терминах $\mathcal{O}$ от числа итераций.
1. Характер сходимости градиентного спуска для гладких выпуклых функций в терминах $\mathcal{O}$ от числа итераций.
1. Характер сходимости градиентного спуска для гладких сильно выпуклых функций в терминах $\mathcal{O}$ от числа итераций.
1. Связь PL-функций и сильно выпуклых функций.
<!-- Лекция 9: Нижние оценки. Тяжёлый шарик, Нестеров -->
1. Нижние оценки для минимизации гладких выпуклых функций с помощью методов первого порядка в терминах $\Omega$ от числа итераций.
1. Нижние оценки для минимизации гладких сильно выпуклых функций с помощью методов первого порядка в терминах $\Omega$ от числа итераций.
1. Отличие ускоренной и неускоренной линейной сходимости методов первого порядка.
1. Метод тяжёлого шарика (Поляка) для сильно выпуклой квадратичной функции. Характер сходимости. Оптимальные гиперпараметры.
1. Локальная и глобальная сходимость численного метода оптимизации.
1. Ускоренный градиентный метод Нестерова для выпуклых гладких функций. Характер сходимости в терминах $\mathcal{O}$ от числа итераций.
1. Ускоренный градиентный метод Нестерова для сильно выпуклых гладких функций. Характер сходимости в терминах $\mathcal{O}$ от числа итераций.
<!-- Лекция 10: Сопряжённые градиенты -->
1. $A$-сопряжённость ($A$-ортогональность) векторов. Скалярное произведение $\langle \cdot, \cdot \rangle_A$.
1. Процесс ортогонализации Грама-Шмидта.
1. Метод сопряжённых направлений (CD).
1. Метод сопряжённых градиентов (достаточно выписать формулы одной итерации).
1. Характер сходимости метода сопряжённых градиентов для сильно выпуклой квадратичной функции в терминах $\mathcal{O}$ от числа итераций метода.
1. Зависимость сходимости метода сопряжённых градиентов от спектра матрицы $A$.
<!-- Лекция 11: Ньютон. Квазиньютон -->
1. Липшицева парабола для гладкой функции.
1. Связь спектра гессиана с константами сильной выпуклости и гладкости функции. Число обусловленности.
1. Метод Ньютона.
1. Сходимость метода Ньютона для квадратичной функции.
1. Характер сходимости метода Ньютона для сильно выпуклых гладких функций — куда и как сходится.
1. Демпфированный метод Ньютона.
1. Метод SR-1 (без точной формулы).
<!-- Лекция 12: Ограничения. Проекция, Франк-Вульф, зеркальный спуск -->
1. Проекция точки на множество.
1. Достаточное условие существования проекции точки на множество.
1. Достаточное условие единственности проекции точки на множество.
1. Критерий проекции точки на выпуклое множество (неравенство Бурбаки-Чейни-Гольдштейна).
1. Оператор проекции как нерастягивающий оператор.
1. Метод проекции градиента.
1. Характер сходимости метода проекции градиента для гладких выпуклых функций в терминах $\mathcal{O}$ от числа итераций метода.
1. Характер сходимости метода проекции градиента для гладких сильно выпуклых функций в терминах $\mathcal{O}$ от числа итераций метода.
1. Метод Франк-Вульфа.
1. Характер сходимости метода Франк-Вульфа для гладких выпуклых функций в терминах $\mathcal{O}$ от числа итераций метода.
1. Характер сходимости метода Франк-Вульфа для гладких сильно выпуклых функций в терминах $\mathcal{O}$ от числа итераций метода.
1. Нижние оценки для условной оптимизации с помощью оракула линейной минимизации (LMO) для гладких сильно выпуклых функций в терминах $\Omega$ от числа итераций метода.
<!-- Лекция 13: Субградиент. Субградиентный метод -->
1. Привести пример выпуклой негладкой задачи линейных наименьших квадратов (возможно, с регуляризацией).
1. Субградиент. Субдифференциал.
1. Субдифференциал поточечного максимума выпуклых функций (теорема Дубовицкого-Милютина).
1. Субградиентный метод.
1. Какому условию должна удовлетворять стратегия выбора шага, чтобы субградиентный метод сходился для выпуклых липшицевых функций?
1. Характер сходимости субградиентного метода для негладких выпуклых липшицевых функций в терминах $\mathcal{O}$ от числа итераций. Стратегия выбора шага.
1. Характер сходимости субградиентного метода для негладких сильно выпуклых липшицевых функций в терминах $\mathcal{O}$ от числа итераций. Стратегия выбора шага.
1. Нижние оценки для негладкой выпуклой оптимизации методами первого порядка в терминах $\Omega$ от числа итераций.
1. Нижние оценки для негладкой сильно выпуклой оптимизации методами первого порядка в терминах $\Omega$ от числа итераций.
<!-- Лекция 14: Проксимальный метод -->
1. Проксимальный оператор $\operatorname{prox}_{f,\alpha}$.
1. Оператор проекции как частный случай проксимального оператора.
1. Аналитическое выражение для $\operatorname{prox}_{\lambda\|x\|_1}$.
1. Аналитическое выражение для $\operatorname{prox}_{\frac{\lambda}{2}\|x\|_2^2}$.
1. Проксимальный оператор как нерастягивающий оператор.
1. Характер сходимости проксимального градиентного метода для гладких выпуклых функций $f$ в терминах $\mathcal{O}$ от числа итераций метода.
1. Характер сходимости проксимального градиентного метода для гладких сильно выпуклых функций $f$ в терминах $\mathcal{O}$ от числа итераций метода.
1. Характер сходимости ускоренного проксимального градиентного метода для гладких выпуклых функций $f$ в терминах $\mathcal{O}$ от числа итераций метода.
<!-- Лекция 15: SGD -->
1. Метод стохастического градиентного спуска.
1. Идея мини-батча. Эпоха.
1. Характер сходимости стохастического градиентного спуска для гладких выпуклых функций в терминах $\mathcal{O}$ от числа итераций.
1. Характер сходимости стохастического градиентного спуска для гладких PL-функций в терминах $\mathcal{O}$ от числа итераций.
1. Характер работы стохастического градиентного спуска с постоянным шагом для гладких PL-функций.
<!-- Лекция 16: Редукция дисперсии: SAG, SVRG, SAGA -->
1. Метод SAG (Stochastic Average Gradient).
<!-- Лекция 17: Адаптивные методы. Muon, Shampoo -->
1. Метод AdamW.
1. Сопряжённая (двойственная) норма.
1. Linear Minimization Oracle (LMO).
1. Связь LMO с сопряжённой нормой.
1. Неевклидов градиентный спуск.
1. Неевклидов нормированный градиентный спуск.
1. Неевклидов градиентный спуск в случае, когда аргумент — матрица.
1. Неевклидов нормированный спуск в случае, когда аргумент — матрица.
1. Полярный фактор матрицы.
1. LMO для спектральной нормы.
1. Формулировка метода нормированного спуска в норме Фробениуса.
1. Формулировка метода нормированного спуска в поэлементной $\ell_\infty$-норме.
1. Формулировка метода нормированного спуска в спектральной норме.
1. Метод Muon.
1. Итерации Ньютона-Шульца для вычисления полярного фактора.
<!-- Лекция 18: Большие модели -->
1. Сколько памяти занимают веса крупнейшей открытой модели (DeepSeek V4-Pro, $\approx 1{,}6$ трлн параметров) в форматах FP32, FP16, BF16?
1. Сколько токенов в обучающей выборке приходилось на модель Chinchilla на один обучаемый параметр модели?
1. Идея warmup в расписании learning rate.
1. Идея аккумуляции градиентов.
1. Дообучение с помощью LoRA-адаптеров.
1. Идея проекции функции потерь нейронной сети на прямую и на плоскость.
1. Grokking.
1. Double Descent.
<!-- Лекция 19: Двойственные методы. ALM, ADMM -->
1. Сопряжённая функция $f^*$.
1. Метод двойственного градиентного подъёма (dual ascent).
1. Связь сильной выпуклости функции $f$ и липшицевости градиента сопряжённой $f^*$.
1. Идея двойственной декомпозиции (dual decomposition).
1. Метод модифицированной функции Лагранжа (ALM).
1. Метод ADMM.

# Теоремы с доказательствами
<!-- Лекция 1: Линейная алгебра. Скорости сходимости -->
1. Тест корней для определения скорости сходимости последовательности.
<!-- Лекция 2: Дифференцирование. Линейный поиск -->
1. Скорость сходимости метода дихотомии для унимодальных функций.
1. Скорость сходимости метода золотого сечения для унимодальных функций.
<!-- Лекция 3: Автоматическое дифференцирование -->
1. Автоматическое дифференцирование. Вычислительный граф. Алгоритмы прямого (forward) и обратного (reverse) режима (без доказательств; описать алгоритмы подробно).
<!-- Лекция 4: Выпуклость. PL. Сильная выпуклость -->
1. Выпуклость надграфика как критерий выпуклости функции.
<!-- Лекция 5: Критерии сильной выпуклости. Условия оптимальности -->
1. Дифференциальный критерий сильной выпуклости первого порядка (доказательство).
1. Дифференциальный критерий сильной выпуклости второго порядка (доказательство).
1. Необходимое условие безусловного экстремума первого порядка (доказательство).
1. Достаточные условия безусловного экстремума второго порядка (доказательство).
<!-- Лекция 7: Линейное программирование. Симплекс -->
1. Теорема о проверке оптимальности решения в задаче линейного программирования.
1. Теорема о сильной двойственности в задаче ЛП.
<!-- Лекция 8: Градиентный спуск. Сходимость -->
1. Теорема сходимости градиентного спуска для гладких выпуклых функций.
1. Теорема сходимости градиентного спуска для гладких PL-функций.
1. Сходимость градиентного спуска для сильно выпуклых квадратичных функций. Оптимальные гиперпараметры.
<!-- Лекция 10: Сопряжённые градиенты -->
1. Доказательство сходимости метода сопряжённых градиентов и вывод формул метода (за какое число шагов сходится метод, как выбираются направления и почему в $A$-ортогонализации достаточно хранить лишь предыдущее направление).
<!-- Лекция 11: Ньютон. Квазиньютон -->
1. Теорема о локальной квадратичной сходимости метода Ньютона для сильно выпуклых функций с липшицевым гессианом.
1. Вывод формул обновления оценок гессиана и обратного гессиана в квазиньютоновских методах SR1, DFP, BFGS.
<!-- Лекция 12: Ограничения. Проекция, Франк-Вульф, зеркальный спуск -->
1. Теорема о сходимости метода проекции градиента для гладких выпуклых функций.
1. Теорема о сходимости метода проекции градиента для гладких сильно выпуклых функций.
1. Теорема о сходимости метода Франк-Вульфа для гладких выпуклых функций.
<!-- Лекция 13: Субградиент. Субградиентный метод -->
1. Теорема о сходимости субградиентного метода для выпуклых липшицевых функций. Стратегии выбора шага для сходимости.
1. Теорема о сходимости субградиентного метода для сильно выпуклых липшицевых функций.
<!-- Лекция 14: Проксимальный метод -->
1. Теорема о сходимости проксимального градиентного метода для выпуклой гладкой функции $f$.
1. Теорема о сходимости проксимального градиентного метода для сильно выпуклой гладкой функции $f$.
<!-- Лекция 15: SGD -->
1. Теорема о сходимости SGD для гладких PL-функций с постоянным и убывающим шагом.
